### ISSUE TITLE
Providing download links for the data examples

### ISSUE THREAD

**Issue by rfezzani** [tsubo164/Fujiyama-Renderer#2]
Hello, and first of all congratulation for this impressive work.
Every thing compiles smoothly with a minimum of effort: a really good job!

I just point here a detail that can make easier running the test: is it possible to provide (in the README file for example) links for downloading the ply, obj, mesh, hdr and jpg files listed in tests/generate_all_data.py?
Providing some instructions concerning this in the README or INSTALL file could be also of great help.

By the way, thanks again for this great job.

**Comment by tsubo164** [comment]
Hi, thank you for letting me know this.
Your point is really great idea. I will sort this thing out.
In next release, I plan to change all python scene script so that
users don't need to explicitly convert input data before running them.

So tests/generate_all_data.py will be more developers-purpose.
Anyway, links and instructions will be included.


2015-03-06 8:44 GMT-08:00 rfezzani <notifications@github.com>:

**Comment by tsubo164** [comment]
Hi, I released a new version and the link to the download page is in README file now.
Thanks!

**Comment by elkhalafy** [comment]
Your Gmail email for important subject, Hiroshi Tsubokawa please

Thank you
